apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: harvesthelper-tls-cert
spec:
  secretName: harvesthelper-tls
  issuerRef: 
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "harvesthelper.westeurope.cloudapp.azure.com"