apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: Somsenduarte@gmail.com
    privateKeySecretRef: 
      name: letsgencrypt-prod
    solvers: 
      - http01:
          ingress:
            class: nginx